"""create a score table

Revision ID: 2d6ba9ceffa8
Revises: 
Create Date: 2021-02-16 14:57:42.426759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6ba9ceffa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ascoreresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('slik_result', sa.String(length=20), nullable=True),
    sa.Column('aip_score', sa.Integer(), nullable=True),
    sa.Column('aip_result', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ascoreresult_name'), 'ascoreresult', ['name'], unique=False)
    op.create_index(op.f('ix_ascoreresult_reference_id'), 'ascoreresult', ['reference_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ascoreresult_reference_id'), table_name='ascoreresult')
    op.drop_index(op.f('ix_ascoreresult_name'), table_name='ascoreresult')
    op.drop_table('ascoreresult')
    # ### end Alembic commands ###
