"""add tenor and occupation

Revision ID: 3e61b3311be3
Revises: 2d6ba9ceffa8
Create Date: 2021-02-19 09:44:28.219295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e61b3311be3'
down_revision = '2d6ba9ceffa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ascoreresult', sa.Column('occupation', sa.String(length=30), nullable=True))
    op.add_column('ascoreresult', sa.Column('req_tnr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ascoreresult', 'req_tnr')
    op.drop_column('ascoreresult', 'occupation')
    # ### end Alembic commands ###
