"""update table names

Revision ID: a8998dc8e38a
Revises: 3e61b3311be3
Create Date: 2021-02-24 10:42:03.718544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8998dc8e38a'
down_revision = '3e61b3311be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorem1table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('req_tnr', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(length=30), nullable=True),
    sa.Column('slik_result', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scorem1table_name'), 'scorem1table', ['name'], unique=False)
    op.create_index(op.f('ix_scorem1table_reference_id'), 'scorem1table', ['reference_id'], unique=True)
    op.drop_index('ix_ascoreresult_name', table_name='ascoreresult')
    op.drop_index('ix_ascoreresult_reference_id', table_name='ascoreresult')
    op.drop_table('ascoreresult')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ascoreresult',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reference_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('slik_result', sa.VARCHAR(length=20), nullable=True),
    sa.Column('aip_score', sa.INTEGER(), nullable=True),
    sa.Column('aip_result', sa.VARCHAR(length=20), nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=30), nullable=True),
    sa.Column('req_tnr', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ascoreresult_reference_id', 'ascoreresult', ['reference_id'], unique=1)
    op.create_index('ix_ascoreresult_name', 'ascoreresult', ['name'], unique=False)
    op.drop_index(op.f('ix_scorem1table_reference_id'), table_name='scorem1table')
    op.drop_index(op.f('ix_scorem1table_name'), table_name='scorem1table')
    op.drop_table('scorem1table')
    # ### end Alembic commands ###
